# Generated by Django 5.0.2 on 2024-03-11 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Question', '0001_initial'),
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.subject'),
        ),
        migrations.AddField(
            model_name='choice',
            name='id_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Question.question'),
        ),
        migrations.AddField(
            model_name='questionhint',
            name='id_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Question.question'),
        ),
        migrations.AddField(
            model_name='questiontest',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Question.question'),
        ),
        migrations.AddField(
            model_name='questiontest',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(through='Question.QuestionTest', to='Test.test'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='id_choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Question.choice'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='id_do_test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Test.dotest'),
        ),
    ]
