# Generated by Django 5.0.2 on 2024-03-11 03:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1b01e178-3bf1-46cc-a1dc-670868e35b99'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d6b04377-7599-43d9-bdf5-18178a833af6'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c8a07f99-1337-406c-9b01-d4be92557ea5'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('846c7ca2-e2cc-4d57-8579-6aedcdcd67f9'), editable=False),
        ),
    ]
