# Generated by Django 5.0.2 on 2024-03-13 04:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0005_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('01b4418a-784a-4410-83d5-797512677355'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc4eb7c5-6998-4f42-8484-837e3ea415c9'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('047eeafd-a535-4bb8-a61c-86efbf74db61'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9659ce0b-b31b-4fa1-bb41-c39a1d128edd'), editable=False),
        ),
    ]
