# Generated by Django 5.0.2 on 2024-03-14 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0006_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2bf86be1-4df7-4bec-8a57-ec0fe0ece56a'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d38977c1-7289-498e-9627-137f147a4b08'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7e695781-55af-450b-a078-9cda56935069'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ee406e1c-2946-462b-83a0-89b1c135f62c'), editable=False),
        ),
    ]
