# Generated by Django 5.0.2 on 2024-03-20 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0007_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b633194b-e5ea-4b9b-8f3c-7615c2bef8dd'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b7fed3ee-a3ce-4b17-addc-093df675fc22'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3cf227fd-c52c-4e10-9e9a-04f187ded828'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('93c14d02-25bc-4d0e-bc5b-9494a0dd16e4'), editable=False),
        ),
    ]
