# Generated by Django 5.0.2 on 2024-03-20 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0008_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('63c77252-ccb0-43a0-a1a3-4965b9e55b99'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cf7a638b-4b4d-46cd-a99c-e0609e1ff032'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6417215-47ac-4e5e-a2a9-aee3878e6753'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a2befb7e-d600-4afb-af53-47b8b6b9a04c'), editable=False),
        ),
    ]
