# Generated by Django 5.0.2 on 2024-03-20 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0009_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c94137b2-dfc9-407c-89b0-1c9fd2039ad6'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3de2f839-2dbf-4ea4-aaaf-c63756512693'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a79655a4-d208-45f0-916d-f433c88eabc5'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7ec199ff-357c-4a25-ba88-5c3d288fe59c'), editable=False),
        ),
    ]
