# Generated by Django 5.0.2 on 2024-03-26 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0011_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d4545614-1b98-404c-802b-ba69ba1d28e3'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7d0f7d83-7950-4697-ac80-bb5b2736b312'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('064e69a0-2253-4daa-b9e0-11ca695af90c'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f333b8d2-495f-4ca7-aca3-00b314a0df12'), editable=False),
        ),
    ]
