# Generated by Django 5.0.2 on 2024-03-26 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0015_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8e4150f8-994a-45d7-9a96-c3efcaa078f9'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0b13f75e-4357-4e04-b855-0c1716cca696'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d07b03be-3928-4a81-8ba8-9921b4a469df'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e4ca9bcd-6ef8-4ec1-aaad-567c6ced3145'), editable=False),
        ),
    ]
