# Generated by Django 5.0.3 on 2024-04-03 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0018_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9fc593a0-7b08-456a-8683-ebf86484b53d'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('97b537da-33e1-4624-ba42-f310dd72b601'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('258103d1-92b6-4909-9f4f-711f1fa8dcbe'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7ec161c6-acc4-4d3e-985f-4f663c6c7f89'), editable=False),
        ),
    ]
