# Generated by Django 5.0.3 on 2024-04-09 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0019_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='rtf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='rtf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionhint',
            name='rtf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionsolution',
            name='rtf',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc7d8acf-aba8-493c-8a90-5b0c1524921b'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb623523-ec63-4090-aeb5-95992a51d34e'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('03a7926d-a3e3-4dd0-aa69-17653a7f3e6e'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('161e836b-1fdf-46b1-b4a1-ff458c98b7ec'), editable=False),
        ),
    ]
