# Generated by Django 5.0.3 on 2024-04-15 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0020_choice_rtf_question_rtf_questionhint_rtf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('99b096ba-0c93-4e43-9f23-877d708f970c'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8842f95e-1241-4422-bb09-21dc3db92d67'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b1cfb595-49ac-42c3-944d-ecc7a2cebac0'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b3ae9d69-06a8-455d-9085-44afa2dfb528'), editable=False),
        ),
    ]
