# Generated by Django 5.0.3 on 2024-04-15 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0021_alter_choice_uuid_alter_question_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('470822ee-8a11-4d08-bf9d-dbfd9238d796'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e5931426-f9ba-4a7b-a1e9-d9c397b775f5'), editable=False),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5c4b89e6-cf5a-4b6c-95c5-8177a7429e9e'), editable=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8e4fc656-3777-454f-bb90-48a06039a2da'), editable=False),
        ),
    ]
