# Generated by Django 5.0.2 on 2024-03-11 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Test', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dotest',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='id_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.subject'),
        ),
        migrations.AddField(
            model_name='test',
            name='id_user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ManyToManyField(through='Test.DoTest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dotest',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test'),
        ),
    ]
