# Generated by Django 5.0.2 on 2024-03-13 04:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_alter_dotest_uuid_alter_subject_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotest',
            name='time_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dotest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4aab254b-8e3f-4878-95f1-eeab9b319474'), editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9d8338b4-82ea-47cd-b04d-139e17ffc732'), editable=False),
        ),
    ]
