# Generated by Django 5.0.2 on 2024-03-20 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_rename_favouritetest_favoritetest_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3a4dbf7e-9464-4a9d-8f24-138c03295d1c'), editable=False),
        ),
    ]
