# Generated by Django 5.0.2 on 2024-03-26 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3b4123f7-c3ec-46f4-8b10-da40e4647385'), editable=False),
        ),
    ]
