# Generated by Django 5.0.2 on 2024-03-26 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0010_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2f0a34b9-2387-41f5-b84b-8dab1cb58492'), editable=False),
        ),
    ]
