# Generated by Django 5.0.2 on 2024-03-26 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0013_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f321d18d-83c9-45d8-b087-e8b5fc58f497'), editable=False),
        ),
    ]
