# Generated by Django 5.0.2 on 2024-03-26 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0014_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ce249617-4678-48ae-a176-8ca1bf8b700e'), editable=False),
        ),
    ]
