# Generated by Django 5.0.2 on 2024-03-29 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0015_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d3d5fa34-2d98-4814-9b28-16132051dbab'), editable=False),
        ),
    ]
