# Generated by Django 5.0.3 on 2024-04-01 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0016_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('95b97891-7ad1-46de-94f6-0b564c03573d'), editable=False),
        ),
    ]
