# Generated by Django 5.0.3 on 2024-04-03 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0017_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('11473350-f815-4944-b536-0b66cf976966'), editable=False),
        ),
    ]
