# Generated by Django 5.0.3 on 2024-04-09 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0018_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8614a0b1-dac8-442d-a5d6-f5292e2ca859'), editable=False),
        ),
    ]
