# Generated by Django 5.0.3 on 2024-04-15 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0020_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('06e53d95-4df2-4ea4-b9c6-9e9c5e8a205b'), editable=False),
        ),
    ]
