"""
Django settings for Online_Test_Management project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from os import environ
import os
from pathlib import Path

import django

import cloudinary
import cloudinary.uploader
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-88vcrq)abdk^o_v9j_+8(+62^cqv=+erf3@a1-3ud2$7a^goa!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.1.9', '192.168.1.103', '192.168.1.15']
ALLOWED_HOSTS = []
# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'User',
    'Question',
    'Test',
    'Core',
    'Practice',
    'Teacher',
    'Comment',
    'rest_framework',
    'django.contrib.admin',
    'tz_detect',
    'debug_toolbar',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tz_detect.middleware.TimezoneMiddleware',
]

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = 'Online_Test_Management.urls'

template_dir = [
    # os.path.join(BASE_DIR, 'Online_Test_Management', 'templates'),
    os.path.join(BASE_DIR, 'Core', 'templates'),
    os.path.join(BASE_DIR, 'Question', 'templates'),
    os.path.join(BASE_DIR, 'Test', 'templates'),
    os.path.join(BASE_DIR, 'Practice', 'templates'),
    os.path.join(BASE_DIR, 'User', 'templates'),
    os.path.join(BASE_DIR, 'Teacher', 'templates'),
    os.path.join(BASE_DIR, 'Comment', 'templates'),
    # os.path.join(BASE_DIR, 'templates'),
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [*template_dir],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Online_Test_Management.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

NS_TEST_DB_HOST = "localhost"
if environ.get('NS_TEST_DB_HOST') is not None:
    NS_TEST_DB_HOST = environ.get('NS_TEST_DB_HOST')
NS_TEST_DB_PORT = "5432"
if environ.get('NS_TEST_DB_PORT') is not None:
    NS_TEST_DB_PORT = environ.get('NS_TEST_DB_PORT')
NS_TEST_DB_NAME = "Online_Test_Project"
if environ.get('NS_TEST_DB_NAME') is not None:
    NS_TEST_DB_NAME = environ.get('NS_TEST_DB_NAME')
NS_TEST_DB_SCHEMA = "public"
if environ.get('NS_TEST_DB_SCHEMA') is not None:
    NS_TEST_DB_SCHEMA = environ.get('NS_TEST_DB_SCHEMA')
NS_TEST_DB_USER = "postgres"
if environ.get('NS_TEST_DB_USER') is not None:
    NS_TEST_DB_USER = environ.get('NS_TEST_DB_USER')
NS_TEST_DB_PASSWORD = "postgres2508"
if environ.get('NS_TEST_DB_PASSWORD') is not None:
    NS_TEST_DB_PASSWORD = environ.get('NS_TEST_DB_PASSWORD')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'OPTIONS': {
            'options': str('-c search_path=%s,public' % NS_TEST_DB_SCHEMA)
        },

        'NAME': NS_TEST_DB_NAME,
        'USER': NS_TEST_DB_USER,
        'PASSWORD': NS_TEST_DB_PASSWORD,
        'HOST': NS_TEST_DB_HOST,
        'PORT': NS_TEST_DB_PORT,
        'TEST': {
            'NAME': NS_TEST_DB_NAME,
            'USER': NS_TEST_DB_USER,
            'PASSWORD': NS_TEST_DB_PASSWORD,
            'HOST': NS_TEST_DB_HOST,
            'PORT': NS_TEST_DB_PORT,
            'SCHEMA': "test",
            # 'OPTIONS': {
            #     'options': str('-c search_path=%s' % "test")
            # },
        }

    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'User.User'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Bangkok'  # Replace 'Asia/Bangkok' with your timezone
TIME_ZONE = 'UTC'
USE_TZ = True

USE_I18N = True

USE_L10N = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

cloudinary.config(
    cloud_name="dvi9ihpbc",
    api_key="135497366991663",
    api_secret="EYQ5NPzEGALn1jIHLnSB9zds17E"
)
