# Generated by Django 5.0.2 on 2024-03-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_testcomment_id_parent_alter_likecomment_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcomment',
            name='id_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='Comment.testcomment'),
        ),
    ]
