# Generated by Django 5.0.3 on 2024-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0007_imagecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
